name: Build and Release

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Installing Node Dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Installing PyPi Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Cursors
        run: |
          npx cbmp --version
          yarn render
          clickgen --version
          ctgen --version
          yarn build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cursor-packages
          path: bin/
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: cursor-packages
          path: bin/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*.tar.xz
            bin/*.zip
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
